// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzahdqtydcahikdvzwhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWhkcXR5ZGNhaGlrZHZ6d2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNjIwNTcsImV4cCI6MjA1NTgzODA1N30.ooAGfESkkS2jII0iH8ZzRTQFsisIeTJdMdNXQsJdhx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);